name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        uses: natescherer/publish-powershell-action@v1
        with:
          token: ${{ secrets..PS_GALLERY_API_KEY }}
          target: gallery
          path: Stucco
